runs:
  using: "composite"
  steps:
    - name: install pnpm
      uses: pnpm/action-setup@v2.0.1
      id: pnpm-install
      with:
        version: 7
        run_install: false

    - name: get pnpm store directory
      id: pnpm-cache-dir
      run: |
        echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

    - name: pnpm cache
      uses: actions/cache@v3
      id: pnpm-cache
      with:
        path: |
          **/node_modules
          ${{ steps.pnpm-cache-dir.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
