name: 'Deploy'

on:
  push:
    branches:
     - next

jobs:
  dependencies:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: ./.github/actions/pnpm

    - name: install dependencies
      if: steps.pnpm-cache.outputs.cache-hit != 'true'
      run: pnpm install --frozen-lockfile --prefer-offline --ignore-scripts

  package1:
    needs: [dependencies]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: ./.github/actions/pnpm

    - run: pnpm --filter=package1 build

  package2:
    needs: [dependencies]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: ./.github/actions/pnpm

    - run: pnpm --filter=package2 build

  package3:
    needs: [dependencies]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: ./.github/actions/pnpm

    - run: pnpm --filter=package3 build

