name: 'Deploy'

on:
  push:
    branches:
     - next

jobs:
  dependencies:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install pnpm
      uses: pnpm/action-setup@v2.0.1
      id: pnpm-install
      with:
        version: 7
        run_install: false

    - name: get pnpm store directory
      id: pnpm-cache
      run: |
        echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: |
          **/node_modules
          ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: install dependencies
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: pnpm install --frozen-lockfile --prefer-offline --ignore-scripts
