name: Deploy

on:
  push:
    branches:
      - next

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        node: [16]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          check-latest: true

      - name: Install global dependencies
        run: |
          npm i -g @cloudflare/wrangler

      - name: Get yarn cache directory path
        id: yarn-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install yarn dependencies
        run: yarn install --freeze-lockfile

      - name: Run linter
        run: yarn lint --since

      - name: Run unit tests
        run: yarn test:unit --since

      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: |
            import getChangesets from '@changesets/read'
            return getChangeSets(process.cwd())

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: '[CI] Release'
          pr_body: 'teste'
