name: Deploy

on:
  push:
    branches:
      - next

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          check-latest: true

      - name: Install global dependencies
        run: |
          npm i -g @cloudflare/wrangler

      - name: Get yarn cache directory path
        id: yarn-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install yarn dependencies
        run: yarn install --freeze-lockfile

      - name: Run linter
        run: yarn lint --since

      - name: Run unit tests
        run: yarn test:unit --since

  release:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ci/release
          fetch-depth: 0

      - name: Update with next branch
        run: |
          git reset --hard origin/next

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          base: master
          branch: ci/release
          commit-message: '[CI] create release'
          title: '[CI] Release'
          body: |
            ## Release PRs

            @<usuario>
            - #<numero do PR>
